BookEx/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import *
from book.views import *
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('admin/', admin.site.urls),
    path('register/',RegisterView.as_view(),name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', HomeView.as_view(), name='home'),
    path('', include('user.urls')),
    path('book/', include('book.urls')),
    path('chat/', include('chat.urls')),
    path('api/', include('api.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "book.views.page_not_found_view"

api/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    path('register/', views.RegisterView.as_view()),
    path('login/', views.LoginView.as_view()),
    path('logout/', views.LogoutView.as_view()),
    path('profile/', views.ProfileView.as_view()),
    path('password/reset/', views.PasswordResetView.as_view()),
    path('password/reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmAPIView.as_view(),
         name='password_reset_confirm'),

    path('regions/<int:country_id>/', views.RegionListView.as_view()),
    path('countries/', views.CountryListView.as_view()),
    path('my-books/<status>/', views.BookListCreateView.as_view()),
    path('my-books/<str:status>/<int:pk>/', views.BookDetailView.as_view()),
    path('all-books/', views.AllBookListView.as_view()),
    path('home/', views.HomeView.as_view())
]

user/urls.py
from django.urls import path
from .views import ProfileView, CustomPasswordResetView, regions_by_country
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

urlpatterns = [
    path('profile/<uuid:pk>/', ProfileView.as_view(), name='profile'),
    path('regions-by-country/', regions_by_country, name='regions'),
    path('password-reset/', CustomPasswordResetView.as_view(template_name='user/password_reset.html'),
         name='password-reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
import uuid
from django.urls import reverse_lazy

Gender = [
    ('M', 'Male'),
    ('F', 'Female')
]


class Country(models.Model):
    name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=100, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True, related_name='regions')

    def __str__(self):
        return self.name


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        '''Create and save a user with the given email, and
        password.
        '''
        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must have is_staff=True.'
            )
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must have is_superuser=True.'
            )

        return self._create_user(email, password, **extra_fields)


class MyUser(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    email = models.EmailField(unique=True, max_length=255, blank=False)
    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last_name"), max_length=150, blank=True)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=Gender, blank=True, null=True)
    profile_pic = models.ImageField(upload_to='profile-pics/', default='profile-pics/default_pic.jpg', null=True,
                                    blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, blank=True)
    education = models.CharField(max_length=100, blank=True, null=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into '
            'this admin site.'
        ),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be '
            'treated as active. Unselect this instead '
            'of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(
        _('date joined'),
        default=timezone.now,
    )

    # Add additional fields here if needed
    objects = UserManager()

    USERNAME_FIELD = 'email'

    def get_absolute_url(self):
        return reverse_lazy('profile', kwargs={'pk': self.pk})

    def __str__(self):
        return self.email

user/forms.py
from django import forms
from .models import MyUser, Region
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth import password_validation
from .models import Country

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    country = forms.ModelChoiceField(queryset=Country.objects.all())
    region = forms.ModelChoiceField(queryset=Region.objects.all())


    class Meta:
        model = get_user_model()
        fields = ['email', 'country', 'region', 'education', 'password1', 'password2']

    def clean_email(self):
        if MyUser.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(f"The {self.cleaned_data['email']} has already registerd")
        return self.cleaned_data['email']


    def clean_region(self, *args, **kwargs):
        if self.cleaned_data.get('region') not in Region.objects.filter(country=self.cleaned_data.get('country')):
            raise forms.ValidationError('This region isnt the part of selected country')
        return self.cleaned_data.get('region')


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )


class ProfileForm(UserChangeForm):
    email = forms.EmailField()
    country = forms.ModelChoiceField(required=True,
                                     queryset=Country.objects.all(),

                                     )
    region = forms.ModelChoiceField(required=True,
                                    queryset=Region.objects.all(),
                                    )
    class Meta:
        model = MyUser
        fields = ['email', 'first_name', 'last_name', 'country', 'region', 'education', 'profile_pic', 'gender', 'age']

    def clean_region(self, *args, **kwargs):
        if self.cleaned_data.get('region') not in Region.objects.filter(country=self.cleaned_data.get('country')):
            raise forms.ValidationError('This region isnt the part of selected country')
        return self.cleaned_data.get('region')

user/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import UpdateView, CreateView
from .models import *
from django.contrib import messages
from .forms import RegisterForm, LoginForm, ProfileForm
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.contrib.auth.views import PasswordResetView
from user.tasks import send_password_reset_email
from django.urls import reverse
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.shortcuts import get_object_or_404

class RegisterView(CreateView):
    model = MyUser
    template_name = 'user/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['countries'] = Country.objects.all()
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f"{form.cleaned_data['email']} successfully registered")
        return response

    def form_invalid(self, form):
        context = self.get_context_data(form=form, selected_country=form.cleaned_data.get('country'),
                                        selected_region=form.cleaned_data.get('region'))
        return self.render_to_response(context)


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(self.request, 'user/login.html', {'form': form})

    def post(self, request):
        next_page = self.request.GET.get('next')
        form = LoginForm(self.request.POST)
        if form.is_valid():
            user = authenticate(email=form.cleaned_data.get('email'), password=form.cleaned_data.get('password'))
            if user:
                login(self.request, user)
                if next_page:
                    return redirect(next_page)
                else:
                    return redirect('home')
            else:
                messages.error(self.request, "Your username or password didn't match.")

        return render(self.request, 'user/login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(self.request)
        messages.success(self.request, 'You are logged out')
        return redirect('login')


class ProfileView(UpdateView):
    model = MyUser
    form_class = ProfileForm
    template_name = 'user/profile.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['countries'] = Country.objects.all()
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Profile updated successfully.")
        return response

    def post(self, request, *args, **kwargs):
        print(1111, self.get_object())
        if self.get_object() != request.user:
            raise PermissionDenied()
        return super().post(request, *args, **kwargs)


def regions_by_country(request):
    regions = list(Region.objects.filter(country_id=request.GET.get('country')).values())
    return JsonResponse({"regions": regions})


class CustomPasswordResetView(PasswordResetView):
    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        try:
            user = MyUser.objects.get(email=email)
        except MyUser.DoesNotExist:
            messages.warning(self.request,'There is no such registered user')
            return redirect('password-reset')
        token_generator = default_token_generator
        token = token_generator.make_token(user)
        uidb64 = urlsafe_base64_encode(force_bytes(user.id))
        reset_link = self.request.build_absolute_uri(
            reverse("password_reset_confirm", kwargs={"uidb64": uidb64, "token": token}))
        subject = 'Password reset request'
        message = f'Hi {user.email},\n\nPlease click the link below to reset your password:\n{reset_link}'
        send_password_reset_email.delay(subject, message, email)  # Trigger Celery task
        return redirect('password_reset_done')

templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'user/profile.css' %}">
{% endblock %}
{% block content %}
    <section class="vh-100" style="background-color: #eee;">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-lg-12 col-xl-11">
            <div class="card text-black" style="border-radius: 25px;">
              <div class="card-body p-md-5">
                <div class="row justify-content-center">
                  <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign in</p>

                    <form method="POST" class="mx-1 mx-md-4">
                        {% csrf_token %}

                      <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                          <label class="form-label" for="form3Example3c">Your Email</label>

                          <input type="email" name="email" required id="form3Example3c" class="form-control" />
                            {% if form.email.errors %}
                              <ul class="errors">
                                {% for error in form.email.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}
                        </div>
                      </div>


                      <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                          <label class="form-label" for="form3Example4c">Password</label>
                        
                          <input type="password" required name="password" id="form3Example4c" class="form-control" />
                            {% if form.password1.errors %}
                              <ul class="errors">
                                {% for error in form.password1.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}
                        </div>
                      </div>


                      <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                        <button type="submit" class="btn btn-primary btn-lg">Sign in</button>
                      </div>
                    </form>
                  				<p>Forgot your password? <a style="color: red" href="{% url 'password-reset' %}"> Reset password</a></p>
                  				<p>Don't have an Account? <a href="{% url 'register' %}"> Register Now!</a></p>


                  </div>
                  <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                      <img src="/media/book-exchange.webp" st class="img-fluid" alt="Sample image">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

templates/user/password_change.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-4">
        <form method="POST">
            {% csrf_token %}
		    <label>Current Password</label>
		    <div class="form-group pass_show">
                <input type="password" name="current_password" class="form-control" placeholder="Current Password">
                {% if form.current_password.errors %}
                              <ul class="errors">
                                {% for error in form.current_password.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                {% endif %}
            </div>
		       <label>New Password</label>
            <div class="form-group pass_show">
                <input type="password" name="new_password1" class="form-control" placeholder="New Password">
                {% if form.new_password1.errors %}
                              <ul class="errors">
                                {% for error in form.new_password1.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                {% endif %}

            </div>
		       <label>Confirm Password</label>
            <div class="form-group pass_show">
                <input type="password" name="new_password2" class="form-control" placeholder="Confirm Password">
                {% if form.new_password2.errors %}
                              <ul class="errors">
                                {% for error in form.new_password2.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                {% endif %}
            </div>
            <br>
            <div class="form-group pass_show">
                        <button type="submit" class="btn btn-primary btn-lg">Register</button>
           </div>
        </form>
		</div>
	</div>
</div>
{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}
{% load custom_filters %}

{% load static %}
{##}
{#<script src="{% static 'user/profile.js' %}" type="application/json" id="regions-url">#}
{#    {#}
{#        "regions_url": "{% url 'regions' %}"#}
{#    }#}
{#</script>#}

{% block css %}
  <link rel="stylesheet" href="{% static 'user/profile.css' %}">

{% endblock %}
{% block js  %}
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
{% endblock %}
{% block content %}
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
            <div class="col-md-3 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px " height="150px" src="{{ profile.profile_pic.url }}"><span class="font-weight-bold">{{ profile.first_name }}</span>
                    <span class="text-black-50">{{ profile.email }}</span>
                    <span>
 </span>
                    <br>
                    {% if request.user != profile %}
<a href="{% url 'chat' profile.email %}"> <button type="button" class="btn btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
  <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"></path>
</svg>
                CHAT
              </button>
    </a>
                    {% endif %}
                </div>
            </div>

            <div class="col-md-5 border-right">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h4 class="text-right">Profile Settings</h4>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                    <div class="col-md-12"><label class="labels">Email</label><input {% if user == profile %} required {% else %} disabled {% endif %} name='email' type="email" class="form-control" value="{{ profile.email }}"></div>
                            {% if form.email.errors %}
                              <ul class="errors">
                                {% for error in form.email.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}

                    <div class="row mt-2">

                        <div class="col-md-6"><label class="labels">Name</label><input {% if user != profile %} disabled{% endif %} name='first_name' type="text" class="form-control" placeholder="first name" value="{{ profile.first_name }}"></div>
                            {% if form.first_name.errors %}
                              <ul class="errors">
                                {% for error in form.first_name.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}


                        <div class="col-md-6"><label class="labels">Surname</label><input {% if user != profile %} disabled {% endif %} name='last_name' type="text" class="form-control" value="{{ profile.last_name }}" placeholder="last name"></div>
                            {% if form.last_name.errors %}
                              <ul class="errors">
                                {% for error in form.last_name.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}
                {% if user == profile %}
                    <div class="row mt-2">
                        <div class="col-md-12"><label for="country-select" class="labels">Country</label>
{#                      <label for="country-select" class="form-label">Country:</label>#}
                      <select required id="country-select" name='country' class="form-select">
                          <option selected value="{{ profile.country.id }}">{{ profile.country.name }}</option>
                          {% for country in countries %}
                        <option value="{{ country.id }}">{{ country.name }}</option>
                          {% endfor %}
                        <!-- add more options for other countries here -->
                      </select>
                    </div>
                        {% if form.country.errors %}
                              <ul class="errors">
                                {% for error in form.country.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}
                    {% else %}
                        <div class="col-md-12"><label class="labels">Country</label><input disabled  type="text" class="form-control" value="{{ profile.country.name }}"></div>

                 {% endif %}
    {#                regions#}
                    <br><br><br>
                    {% if user == profile %}
                    <div class="mb-3">
                    <label for="region-select" class="labels">Regions</label>
                  <select required id="region-select" name="region" class="form-select" name="region">
                          <option selected value="{{ profile.region.id }}">{{ profile.region.name }}</option>
                          {% for region in profile.country.regions.all %}
                              {% if region != profile.region %}
                                <option  value="{{ region.id }}">{{ region.name }}</option>

                              {% endif %}
                          {% endfor %}
                    <!-- add more options for other countries here -->
                  </select>
                    </div>
                        {% if form.region.errors %}
                              <ul class="errors">
                                {% for error in form.region.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}
                    {% else %}
                    <div class="col-md-12"><label class="labels">Region</label><input disabled type="text" class="form-control" value="{{ profile.region.name }}"></div>
                {% endif %}

                        <div class="col-md-12"><label class="labels">Education</label><input {% if user != profile %} disabled {% endif %} required name='education' type="text" class="form-control" {% if profile.education %} value="{{ profile.education }}" {% endif %} placeholder="Study place(example:TUIT)"></div>
                            {% if form.education.errors %}
                              <ul class="errors">
                                {% for error in form.education.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}
                    </div>

                {% if user == profile %}
                    <div class="row mt-3">
                      <div class="form-group mt-3">
                            <label for="id_profile_pic" class="labels">Upload your profile picture:</label>
                            <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic">
                      </div>
                        {% if form.image.errors %}
                              <ul class="errors">
                                {% for error in form.image.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}
                    {% endif %}
                {% if user == profile %}
                        <div style="margin-top: 10px" class="col-md-9">
                             <label for="region-select" class="labels">Gender:</label>
                              <select  name="gender" id="region-select" class="form-select">
                            {% if profile.gender %}
                          <option selected value="{{ profile.gender }}">
                                {% if profile.gender == 'M' %}
                                    Male </option>
                                <option value='F'>Femalae</option>
                                {% else %}
                                Female  </option>
                                <option value='M'>Male</option>

                                {% endif %}
                          {% else %}
                              <option value="">--Select Gender--</option>
                                <option value='M'>Male</option>
                                <option value='F'>Femalae</option>


                      {% endif %}

                                <!-- add more options for other countries here -->
                              </select>
                            {% if form.gender.errors %}
                              <ul class="errors">
                                {% for error in form.gender.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}
                        </div>
                {% else %}
                    <div class="col-md-6"><label class="labels">Gender</label><input disabled type="text" class="form-control" value="{{ profile.gender }}"></div>

                {% endif %}

                        <div class="col-md-6"><label class="labels">AGE</label><input {% if user != profile %} disabled {% endif %} name="age" type="number" min="5"max="100" class="form-control" placeholder="enter your age" value="{{ profile.age }}"></div>
                    </div>
                            {% if form.age.errors %}
                              <ul class="errors">
                                {% for error in form.age.errors %}
                                  <li>{{ error }}</li>
                                {% endfor %}
                              </ul>
                            {% endif %}


                {% if user == profile %}
                    <div class="mt-3"><button class="btn btn-primary profile-button" type="submit">Save Profile</button></div>
                {% endif %}
                </form>

                </div>

            </div>

        </div>
    </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
      const region_select = $("#region-select");
      const country = $("#country-select").val();
      var url = "{% url 'regions' %}";  // generate the URL for the AJAX request


    $("#country-select").change(function() {
     var country = $(this).val();  // get the selected country
       var url = "{% url 'regions' %}";  // generate the URL for the AJAX request
     $.ajax({
       url: url,
       type: "GET",
         data:{"country":country},
       success: function(response) {
           region_select.empty()
         region_select.append("<option value=''>-- Select Region --</option>");

           console.log('FIRSTFIRST',response)
             const data = response['regions'];
                 for (let i = 0; i < data.length; i++) {
                 const option = $('<option>');
                 option.val(data[i]['id']);
                 option.text(data[i]['name']);
                 region_select.append(option);
             }

       },
       error: function(xhr, status, error) {

         console.log("Error: " + error);
       }
     });
    });

  });


</script>

{% endblock %}